/**
 * ConsentGate — blocks access to high-risk features until the user
 * explicitly acknowledges the disclaimer.
 *
 * Usage:
 *   <ConsentGate feature="tax_filing" title="Tax Filing Disclaimer">
 *     <TaxFiling />
 *   </ConsentGate>
 *
 * Consent is stored in localStorage with the document version.
 * When we update a disclaimer, bump the version to force re-acceptance.
 */

import { useState, useEffect } from 'react';
import { Card, CardContent } from '@/components/ui/Card';
import { Button } from '@/components/ui/Button';
import { Switch } from '@/components/ui/Switch';
import { cn } from '@/lib/utils';

const CONSENT_VERSIONS = {
  tax_filing: '2026.03.1',
  payroll: '2026.03.1',
  forensic: '2026.03.1',
  incorporation: '2026.03.1',
  spend_monitor: '2026.03.1',
  financial_health: '2026.03.1',
};

const CONSENT_TEXTS = {
  tax_filing: {
    title: 'Tax Filing — Important Disclaimer',
    points: [
      'Tax returns generated by Astra are drafts for professional review only.',
      'I am solely responsible for the accuracy and completeness of any return lodged with a tax authority.',
      'Astra does not guarantee acceptance by any tax authority. Incorrect filings may result in penalties, interest, or audit.',
      'I will have a registered tax agent, CPA, or qualified tax professional review all returns before lodgement.',
      'Astra and its operators accept no liability for errors in tax filings or resulting penalties.',
    ],
  },
  payroll: {
    title: 'Payroll — Important Disclaimer',
    points: [
      'Payroll calculations are based on published tax tables and may not reflect recent legislative changes.',
      'I am responsible for verifying all pay calculations, withholdings, and superannuation/pension contributions.',
      'This tool does not constitute employment or tax advice.',
      'Incorrect payroll processing may result in penalties, back-pay obligations, or legal action.',
      'I will consult a qualified payroll professional or accountant to verify calculations.',
    ],
  },
  forensic: {
    title: 'Forensic Analysis — Important Disclaimer',
    points: [
      'Forensic findings are investigative aids, not proof of fraud or misconduct.',
      'I will not take legal or disciplinary action based solely on these findings.',
      'Findings must be independently verified by qualified forensic accountants before use in any legal or regulatory context.',
      'The absence of flags does not guarantee the absence of issues.',
      'Astra accepts no liability for actions taken based on forensic analysis outputs.',
    ],
  },
  incorporation: {
    title: 'Company Formation — Important Disclaimer',
    points: [
      'This tool provides general guidance and document templates only — not legal advice.',
      'I will engage a qualified solicitor or corporate advisor before forming any legal entity.',
      'Astra does not register companies with any government authority on my behalf.',
      'Corporate structures and compliance obligations vary by jurisdiction.',
      'I accept full responsibility for entity structure decisions and regulatory compliance.',
    ],
  },
  spend_monitor: {
    title: 'Spend Monitoring — Important Disclaimer',
    points: [
      'Fraud alerts are generated by automated rules and do not confirm misconduct.',
      'I will not take disciplinary or legal action based solely on automated alerts.',
      'I will investigate thoroughly and follow employment and privacy laws before acting on any alert.',
      'False positives can and will occur — alerts require human judgement.',
      'Astra accepts no liability for employment disputes arising from spend monitoring.',
    ],
  },
  financial_health: {
    title: 'Financial Health Score — Important Disclaimer',
    points: [
      'The Financial Health Score is an indicative assessment, not a credit score or valuation.',
      'I will not rely on this score for loan applications, investment decisions, or acquisitions without independent verification.',
      'The score may not reflect all material risks or off-balance-sheet items.',
      'Astra accepts no liability for decisions made based on this score.',
    ],
  },
};

function getConsentKey(feature) {
  return `astra_consent_${feature}`;
}

function hasValidConsent(feature) {
  try {
    const stored = localStorage.getItem(getConsentKey(feature));
    if (!stored) return false;
    const parsed = JSON.parse(stored);
    return parsed.version === CONSENT_VERSIONS[feature] && parsed.accepted === true;
  } catch {
    return false;
  }
}

function recordConsent(feature) {
  localStorage.setItem(getConsentKey(feature), JSON.stringify({
    version: CONSENT_VERSIONS[feature],
    accepted: true,
    accepted_at: new Date().toISOString(),
  }));
}

export default function ConsentGate({ feature, children }) {
  const [accepted, setAccepted] = useState(false);
  const [checked, setChecked] = useState(false);

  useEffect(() => {
    setAccepted(hasValidConsent(feature));
  }, [feature]);

  if (accepted) return children;

  const config = CONSENT_TEXTS[feature];
  if (!config) return children; // No consent required for this feature

  const handleAccept = () => {
    recordConsent(feature);
    setAccepted(true);
  };

  return (
    <div className={cn('min-h-[60vh] flex items-center justify-center')}>
      <Card className="max-w-lg w-full border-2 border-amber-300 shadow-lg">
        <CardContent className="pt-8 pb-8">
          <div className={cn('w-12 h-12 rounded-full bg-amber-100 flex items-center justify-center mx-auto mb-4')}>
            <svg className="w-6 h-6 text-amber-600" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4c-.77-.833-1.964-.833-2.732 0L4.082 16.5c-.77.833.192 2.5 1.732 2.5z" />
            </svg>
          </div>

          <h3 className="text-lg font-bold text-gray-900 text-center mb-4">{config.title}</h3>

          <p className="text-sm text-gray-600 mb-4 text-center">Please read and acknowledge the following before proceeding:</p>

          <Card className="bg-gray-50 border-0 shadow-none mb-6">
            <CardContent className="p-4 space-y-3">
              {config.points.map((point, i) => (
                <div key={i} className="flex gap-2 text-sm text-gray-700">
                  <span className="text-amber-500 font-bold mt-0.5 shrink-0">{i + 1}.</span>
                  <span>{point}</span>
                </div>
              ))}
            </CardContent>
          </Card>

          <label className="flex items-start gap-3 mb-6 cursor-pointer">
            <Switch
              checked={checked}
              onCheckedChange={setChecked}
              className="mt-0.5"
            />
            <span className="text-sm text-gray-700 font-medium">
              I have read and understand the above. I accept that Astra is a software tool and
              that I am responsible for verifying all outputs with qualified professionals.
            </span>
          </label>

          <Button
            onClick={handleAccept}
            disabled={!checked}
            className="w-full"
          >
            I Understand — Proceed
          </Button>

          <p className="text-[10px] text-gray-400 text-center mt-4">
            This acknowledgement is stored locally and linked to your account.
            Full terms at <a href="/terms" className="underline">/terms</a>.
          </p>
        </CardContent>
      </Card>
    </div>
  );
}
