/**
 * Reusable legal disclaimer banners.
 *
 * Usage:
 *   <LegalDisclaimer type="payroll" />
 *   <LegalDisclaimer type="tax" />
 *   <LegalDisclaimer type="ai" />
 *   <LegalDisclaimer type="forensic" />
 *   <LegalDisclaimer type="financial_health" />
 *   <LegalDisclaimer type="spend_monitor" />
 *   <LegalDisclaimer type="incorporation" />
 */

const DISCLAIMERS = {
  payroll: {
    text: 'Payroll calculations are based on published tax tables, award rates, and superannuation/pension rules. Legislation changes frequently and obligations vary by jurisdiction, employee classification, and individual circumstances. This tool does not constitute employment or tax advice. You are responsible for verifying all pay calculations, withholdings, and lodgements. Consult a qualified payroll professional or accountant before processing.',
    severity: 'warning',
  },
  tax: {
    text: 'Tax calculations are based on published rates and rules as of the date shown. Tax law is subject to change, interpretation, and jurisdiction-specific exceptions. These calculations are for informational purposes only and do not constitute tax advice. Always verify with a qualified tax professional before filing.',
    severity: 'warning',
  },
  tax_filing: {
    text: 'Tax returns generated by this system are drafts for review. You are solely responsible for the accuracy and completeness of any return lodged with a tax authority. DavenRoe does not guarantee acceptance by any tax authority. Incorrect filings may result in penalties, interest, or audit. Have a registered tax agent or CPA review all returns before lodgement.',
    severity: 'high',
  },
  ai: {
    text: 'Responses are generated by AI and provided as drafts for human review only. They do not constitute professional accounting, tax, legal, or financial advice. You must verify all information with a qualified professional before making decisions based on these outputs.',
    severity: 'info',
  },
  forensic: {
    text: 'Forensic analysis findings are investigative aids produced by statistical methods. They indicate areas of concern but do not prove fraud, irregularities, or misconduct. Findings must be independently verified by qualified forensic accountants before use in any legal, regulatory, or employment context. The absence of flags does not guarantee the absence of issues.',
    severity: 'warning',
  },
  financial_health: {
    text: 'The Financial Health Score is an indicative assessment based on your accounting data. It is not a credit score, credit rating, or valuation. Do not rely on this score for loan applications, investment decisions, business valuations, or any financial commitment without independent professional verification. Scores may not reflect all material risks.',
    severity: 'warning',
  },
  spend_monitor: {
    text: 'Fraud alerts are generated by automated rules and pattern analysis. An alert does not confirm misconduct — it flags transactions for human review. Do not take disciplinary or legal action based solely on automated alerts. Always investigate thoroughly and follow your jurisdiction\'s employment laws before acting. False positives can and will occur.',
    severity: 'high',
  },
  live_receipt: {
    text: 'Expense categorisation and amount extraction use AI and may contain errors. Always review captured data before approving. You are responsible for the accuracy of expense claims submitted through this system.',
    severity: 'info',
  },
  incorporation: {
    text: 'Company formation tools provide general guidance and document templates only. They do not constitute legal advice. Corporate structures, compliance obligations, and registration requirements vary by jurisdiction and individual circumstances. Engage a qualified solicitor or corporate advisor before forming any legal entity.',
    severity: 'high',
  },
  bank_feed: {
    text: 'Bank feed data is provided by third-party aggregation services and may be incomplete, delayed, or contain errors. Always reconcile against official bank statements.',
    severity: 'info',
  },
};

const SEVERITY_STYLES = {
  info: 'bg-blue-50 border-blue-200 text-blue-700',
  warning: 'bg-amber-50 border-amber-200 text-amber-700',
  high: 'bg-red-50 border-red-200 text-red-700',
};

export default function LegalDisclaimer({ type, className = '' }) {
  const config = DISCLAIMERS[type];
  if (!config) return null;

  const style = SEVERITY_STYLES[config.severity] || SEVERITY_STYLES.info;

  return (
    <div className={`border rounded-lg px-4 py-2.5 text-xs leading-relaxed ${style} ${className}`}>
      <span className="font-semibold">Important:</span> {config.text}
    </div>
  );
}

export function GlobalFooterDisclaimer() {
  return (
    <div className="mt-8 pt-4 border-t border-gray-100 text-[10px] text-gray-400 leading-relaxed text-center">
      DavenRoe is a software tool, not an accounting firm, tax agent, financial advisor, or legal practice.
      All outputs — including AI-generated content, tax calculations, payroll figures, forensic analysis, and financial scores — are
      for informational purposes only and require professional review before reliance.
      DavenRoe and its operators accept no liability for losses arising from use of this software.
      See our <a href="/terms" className="underline hover:text-gray-600">Terms of Service</a> for full details.
    </div>
  );
}
