import { motion } from 'framer-motion';
import { Button } from '@/components/ui/Button';
import { Card, CardContent } from '@/components/ui/Card';
import { cn } from '@/lib/utils';

const fadeUp = {
  hidden: { opacity: 0, y: 20 },
  visible: (i = 0) => ({
    opacity: 1,
    y: 0,
    transition: { duration: 0.5, ease: 'easeOut', delay: i * 0.1 },
  }),
};

export default function Terms({ onBack }) {
  return (
    <div className="bg-white text-gray-900 min-h-screen">
      <nav className="flex items-center justify-between px-6 lg:px-16 py-6 border-b border-gray-100">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-lg bg-indigo-600 flex items-center justify-center">
            <span className="text-white font-bold text-lg">A</span>
          </div>
          <span className="text-xl font-semibold tracking-tight">Astra</span>
        </div>
        <Button variant="ghost" size="sm" onClick={onBack}>
          &larr; Back to homepage
        </Button>
      </nav>

      <div className="max-w-4xl mx-auto px-6 lg:px-16 py-16">
        <motion.div initial="hidden" whileInView="visible" viewport={{ once: true, amount: 0.1 }} variants={fadeUp}>
          <h1 className="text-4xl font-bold mb-2">Terms of Service</h1>
          <p className="text-sm text-gray-400 mb-12">Last Updated: March 2026 &middot; Version 2026.03.3</p>
        </motion.div>

        <motion.div initial="hidden" whileInView="visible" viewport={{ once: true, amount: 0.1 }} variants={fadeUp} custom={1}>
          <Card className="border-amber-200 bg-amber-50 mb-12">
            <CardContent className="p-4">
              <p className="text-sm text-amber-800">
                <strong>Important:</strong> By creating an account, accessing any feature, or using any output from Astra, you agree to these Terms in their entirety. If you do not agree, do not use the service.
              </p>
            </CardContent>
          </Card>
        </motion.div>

        <div className="space-y-10">
          <Section index={2} title="1. Nature of Service">
            <p>
              Astra is an AI-assisted accounting <strong>software tool</strong>, not an accounting firm, registered tax agent, licensed financial advisor, legal practice, or financial institution. Astra does not provide professional accounting advice, tax advice, legal advice, employment advice, or financial advice. No output from Astra — whether generated by AI, deterministic algorithms, or any combination — should be treated as professional advice.
            </p>
          </Section>

          <Section index={3} title="2. AI-Generated Output Disclaimer">
            <h3 className="font-semibold text-gray-900 mt-4 mb-2">2.1 Human Review Required</h3>
            <p>
              All AI-generated outputs — including but not limited to transaction categorisations, financial narratives, tax calculations, payroll figures, forensic analysis findings, financial health scores, spend monitoring alerts, due diligence reports, and incorporation guidance — are <strong>drafts requiring human review and approval</strong> before any reliance or action.
            </p>
            <h3 className="font-semibold text-gray-900 mt-4 mb-2">2.2 No Guarantee of Accuracy</h3>
            <p>
              While Astra uses deterministic logic derived from published legislation for tax and payroll, the law is complex and subject to interpretation. AI outputs are probabilistic and may contain errors, omissions, or hallucinations. <strong>You are solely responsible for verifying all outputs before use.</strong>
            </p>
            <h3 className="font-semibold text-gray-900 mt-4 mb-2">2.3 Not a Substitute for Professional Advice</h3>
            <p>
              Astra does not replace a qualified accountant, registered tax agent, CPA, enrolled agent, payroll specialist, solicitor, or auditor. You must consult appropriately licensed professionals in your jurisdiction.
            </p>
          </Section>

          <Section index={4} title="3. Limitation of Liability">
            <Card className="border-gray-100 bg-gray-50 shadow-none mb-4">
              <CardContent className="p-4">
                <p className="text-xs text-gray-600 uppercase tracking-wide leading-relaxed">
                  TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, ASTRA SHALL NOT BE LIABLE FOR ANY LOSSES, DAMAGES, PENALTIES, FINES, INTEREST, BACK-PAY OBLIGATIONS, OR COSTS ARISING FROM USE OF THE SERVICE.
                </p>
              </CardContent>
            </Card>
            <ul className="space-y-2 text-sm">
              {[
                'Reliance on AI-generated categorisations, calculations, or recommendations',
                'Tax filing errors, omissions, late lodgements, or rejection by a tax authority',
                'Payroll miscalculations including withholdings, super/pension/401(k), or leave',
                'Forensic analysis findings (false positives or missed red flags)',
                'Spend monitoring alerts (false positives or missed fraud)',
                'Financial health score inaccuracies',
                'Company incorporation guidance',
                'Any AI hallucination or erroneous output',
                'Bank feed or receipt scanning errors',
                'System downtime or third-party integration actions',
              ].map((item, i) => (
                <li key={i} className="flex items-start gap-2 text-gray-600">
                  <span className="text-red-400 mt-0.5">&#8226;</span> {item}
                </li>
              ))}
            </ul>
            <p className="mt-4 font-semibold text-sm">
              Liability is capped at the fees paid in the twelve (12) months preceding the claim. No indirect, consequential, exemplary, or punitive damages.
            </p>
          </Section>

          <Section index={5} title="4. Your Responsibilities">
            <ul className="space-y-2">
              {[
                'Review all AI-drafted outputs before approving or acting on them',
                'Verify all tax and payroll calculations with qualified professionals',
                'Maintain your own records independent of Astra',
                'Reconcile bank feed data against official bank statements',
                'Ensure your use complies with all applicable laws',
                'Maintain engagement with qualified professionals for material matters',
              ].map((item, i) => (
                <li key={i} className="flex items-start gap-2 text-gray-600">
                  <span className="text-indigo-500">&#8226;</span> {item}
                </li>
              ))}
            </ul>
          </Section>

          <Section index={6} title="5. Feature-Specific Terms">
            <div className="space-y-4">
              <FeatureTerms title="5.1 Forensic Module" items={[
                'Outputs are investigative aids, not legal evidence.',
                'Findings must be independently verified before legal, regulatory, or employment action.',
                'The absence of flags does not guarantee the absence of fraud.',
              ]} />
              <FeatureTerms title="5.2 Payroll Module" items={[
                'You are solely responsible for verifying all calculations before processing.',
                'Incorrect payroll may result in penalties or legal action. Astra accepts no liability.',
                'Astra does not lodge payroll returns or make super/pension/tax deposits on your behalf.',
              ]} />
              <FeatureTerms title="5.3 Tax Filing Module" items={[
                'Tax returns are drafts for professional review before lodgement.',
                'Astra does not guarantee acceptance by any tax authority.',
              ]} />
              <FeatureTerms title="5.4 Spend Monitoring" items={[
                'Alerts do not confirm misconduct. Always investigate and follow employment law.',
                'You must not take disciplinary action based solely on automated alerts.',
              ]} />
              <FeatureTerms title="5.5 Financial Health Score" items={[
                'Not a credit score, credit rating, or business valuation.',
                'Do not provide to lenders or investors without independent verification.',
              ]} />
              <FeatureTerms title="5.6 Company Incorporation" items={[
                'General guidance and templates only — not legal advice.',
                'Astra does not register companies with any government authority.',
              ]} />
              <FeatureTerms title="5.7 Expense Management" items={[
                'AI receipt scanning may contain errors. Review before approving.',
                'Astra does not validate the legitimacy of expense claims.',
              ]} />
            </div>
          </Section>

          <Section index={7} title="6. Data Ownership & Privacy">
            <p>
              <strong>You own your data.</strong> All financial data, documents, and records remain your property. Data may be processed by third-party providers under their respective terms. Data is never used for AI model training. See our <a href="/privacy" className="text-indigo-600 underline">Privacy Policy</a> for full details.
            </p>
          </Section>

          <Section index={8} title="7. Disclaimer of Warranties">
            <Card className="border-gray-100 bg-gray-50 shadow-none">
              <CardContent className="p-4">
                <p className="text-xs text-gray-600 uppercase tracking-wide leading-relaxed">
                  THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, ACCURACY, AND NON-INFRINGEMENT.
                </p>
              </CardContent>
            </Card>
          </Section>

          <Section index={9} title="8. Indemnification">
            <p>
              You agree to indemnify and hold harmless Astra from any claims, damages, losses, and expenses arising from your use of the service, including claims from your employees, contractors, clients, or counterparties.
            </p>
          </Section>

          <Section index={10} title="9. Dispute Resolution">
            <p className="mb-3">
              <strong>General:</strong> These Terms are governed by the laws of New Zealand. Disputes resolved through binding arbitration under the Arbitration Act 1996 (NZ). Class action waiver applies to the maximum extent permitted by law.
            </p>
            <p>
              <strong>US Users:</strong> See Section 10 for US-specific dispute resolution including AAA arbitration.
            </p>
          </Section>

          {/* US-SPECIFIC SECTION */}
          <motion.div
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true, amount: 0.1 }}
            variants={fadeUp}
            custom={11}
          >
            <Card className="border-2 border-blue-200 bg-blue-50/30">
              <CardContent className="p-6">
                <Section index={0} title="10. United States — Supplemental Terms">
                  <Card className="border-blue-200 bg-blue-100 shadow-none mb-6">
                    <CardContent className="p-4">
                      <p className="text-sm text-blue-800">
                        <strong>US Residents:</strong> If you are located in the United States, these supplemental terms apply and override conflicting general provisions.
                      </p>
                    </CardContent>
                  </Card>

                  <h3 className="font-bold text-gray-900 mt-6 mb-3">10.1 Not a Licensed Professional Service</h3>
                  <p className="mb-3">
                    Astra is <strong>not</strong> a CPA, enrolled agent, registered tax preparer, licensed attorney, registered investment advisor, or any other licensed professional under US federal or state law. No professional relationship is created.
                  </p>
                  <p className="mb-1 font-semibold text-sm text-gray-800">Astra does not:</p>
                  <ul className="space-y-1.5 text-sm mb-4">
                    {[
                      'Prepare tax returns within the meaning of IRC \u00a7 7701(a)(36)',
                      'Provide "tax advice" under IRS Circular 230',
                      'Represent users before the IRS or any state tax authority',
                      'Provide investment advice under the Investment Advisers Act of 1940',
                      'Practice law in any US jurisdiction',
                      'File Forms W-2, 941, 940, 1099, or any payroll tax form on your behalf',
                      'Make deposits to EFTPS or any state tax agency',
                    ].map((item, i) => (
                      <li key={i} className="flex items-start gap-2 text-gray-600">
                        <span className="text-red-400 mt-0.5">&#10005;</span> {item}
                      </li>
                    ))}
                  </ul>

                  <h3 className="font-bold text-gray-900 mt-6 mb-3">10.2 US Tax Disclaimer</h3>
                  <Card className="border-red-200 bg-red-50 shadow-none mb-4">
                    <CardContent className="p-3">
                      <p className="text-xs text-red-700">
                        <strong>IRS Circular 230 Notice:</strong> Astra&apos;s outputs do not constitute a &ldquo;covered opinion&rdquo; or &ldquo;other written advice&rdquo; under Circular 230. You may not rely on Astra&apos;s outputs to avoid penalties under the Internal Revenue Code.
                      </p>
                    </CardContent>
                  </Card>

                  <h3 className="font-bold text-gray-900 mt-6 mb-3">10.3 US Dispute Resolution</h3>
                  <p className="mb-3">
                    Disputes governed by the Federal Arbitration Act (9 U.S.C. &sect;&sect; 1-16). Binding individual arbitration via the American Arbitration Association (AAA). For claims under $10,000, Astra pays all AAA fees.
                  </p>
                  <p className="mb-3 font-semibold text-sm">
                    You waive the right to a jury trial and the right to participate in a class action.
                  </p>
                  <p className="text-sm text-gray-500 mb-4">
                    Opt-out: You may opt out of arbitration within 30 days of account creation by emailing legal@astra.ai. If you opt out, disputes go to state or federal courts in Wilmington, Delaware.
                  </p>

                  <h3 className="font-bold text-gray-900 mt-6 mb-3">10.4 California (CCPA/CPRA)</h3>
                  <p>
                    Astra does <strong>not sell or share</strong> your personal information. See our <a href="/privacy" className="text-indigo-600 underline">Privacy Policy</a> for full CCPA/CPRA disclosures including your right to know, delete, correct, and non-discrimination.
                  </p>

                  <h3 className="font-bold text-gray-900 mt-6 mb-3">10.5 State-Specific Provisions</h3>
                  <p className="text-sm text-gray-600">
                    <strong>California:</strong> &sect; 1542 waiver applies. <strong>New Jersey:</strong> TCCWNA protections preserved. <strong>All states:</strong> Where mandatory consumer protections cannot be waived, those protections apply. Aggregate liability cap (Section 3.2) still applies.
                  </p>

                  <h3 className="font-bold text-gray-900 mt-6 mb-3">10.6 No E&O Coverage for Users</h3>
                  <p className="text-sm text-gray-600">
                    Astra does not carry professional liability insurance for your benefit. If you are an accountant or bookkeeper using Astra for client work, maintain your own E&O insurance and exercise independent professional judgement.
                  </p>
                </Section>
              </CardContent>
            </Card>
          </motion.div>

          {/* AU/NZ SECTION */}
          <Section index={12} title="11. Australia & New Zealand — Supplemental Terms">
            <FeatureTerms title="Australian Consumer Law" items={[
              'Non-excludable consumer guarantees under the ACL are preserved.',
              'Liability for breach of non-excludable guarantees limited to re-supply of the service.',
            ]} />
            <div className="mt-3">
              <FeatureTerms title="New Zealand Consumer Guarantees Act" items={[
                'CGA applies to personal/domestic/household consumers. Business users: CGA contracted out under Section 43.',
              ]} />
            </div>
            <div className="mt-3">
              <FeatureTerms title="Tax Agent Services Act (AU)" items={[
                'Astra is not a registered tax agent or BAS agent under the Tax Agent Services Act 2009.',
                'All outputs are for lodgement by a registered tax agent.',
              ]} />
            </div>
          </Section>

          {/* UK/EU SECTION */}
          <Section index={13} title="12. United Kingdom & EU — Supplemental Terms">
            <FeatureTerms title="Consumer Rights" items={[
              'Statutory rights under Consumer Rights Act 2015 (UK) and EU Consumer Rights Directive are preserved.',
              'Astra is not FCA-regulated and does not provide regulated financial advice.',
              'MTD VAT return generation is a draft tool. Have a registered agent review before submission to HMRC.',
            ]} />
          </Section>

          <Section index={14} title="13. General">
            <p className="mb-3">
              <strong>Changes:</strong> 30 days notice for material changes. Continued use = acceptance.
            </p>
            <p className="mb-3">
              <strong>Severability:</strong> Unenforceable provisions are modified to minimum enforceable extent; remaining provisions continue.
            </p>
            <p className="mb-3">
              <strong>Survival:</strong> Sections 2, 3, 5, 7, 8, 9/10, and this section survive termination.
            </p>
            <p>
              <strong>Force Majeure:</strong> Astra is not liable for failures due to circumstances beyond reasonable control.
            </p>
          </Section>

          <Section index={15} title="14. Contact">
            <p>
              Legal: <span className="text-indigo-600 font-medium">legal@astra.ai</span> &middot;
              Privacy: <span className="text-indigo-600 font-medium">privacy@astra.ai</span> &middot;
              Security: <span className="text-indigo-600 font-medium">security@astra.ai</span>
              <br />
              US-specific legal: <span className="text-indigo-600 font-medium">us-legal@astra.ai</span>
            </p>
          </Section>
        </div>
      </div>
    </div>
  );
}

function Section({ title, children, index = 0 }) {
  return (
    <motion.div
      initial="hidden"
      whileInView="visible"
      viewport={{ once: true, amount: 0.1 }}
      variants={fadeUp}
      custom={index}
    >
      <h2 className="text-xl font-bold text-gray-900 mb-4">{title}</h2>
      <div className="text-gray-600 leading-relaxed">
        {children}
      </div>
    </motion.div>
  );
}

function FeatureTerms({ title, items }) {
  return (
    <Card className="border-gray-100 bg-gray-50 shadow-none">
      <CardContent className="p-3">
        <h4 className="font-semibold text-sm text-gray-800 mb-2">{title}</h4>
        <ul className="space-y-1">
          {items.map((item, i) => (
            <li key={i} className="text-xs text-gray-600 flex items-start gap-1.5">
              <span className="text-gray-400 mt-0.5">&#8226;</span> {item}
            </li>
          ))}
        </ul>
      </CardContent>
    </Card>
  );
}
