export default function Terms({ onBack }) {
  return (
    <div className="bg-white text-gray-900 min-h-screen">
      <nav className="flex items-center justify-between px-6 lg:px-16 py-6 border-b border-gray-100">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-lg bg-indigo-600 flex items-center justify-center">
            <span className="text-white font-bold text-lg">A</span>
          </div>
          <span className="text-xl font-semibold tracking-tight">Astra</span>
        </div>
        <button onClick={onBack} className="text-sm text-gray-500 hover:text-gray-900 transition-colors">
          &larr; Back to homepage
        </button>
      </nav>

      <div className="max-w-4xl mx-auto px-6 lg:px-16 py-16">
        <h1 className="text-4xl font-bold mb-2">Terms of Service</h1>
        <p className="text-sm text-gray-400 mb-12">Last Updated: March 2026 &middot; Version 2026.03.2</p>

        <div className="bg-amber-50 border border-amber-200 rounded-xl p-4 mb-12 text-sm text-amber-800">
          <strong>Important:</strong> By creating an account, accessing any feature, or using any output from Astra, you agree to these Terms in their entirety. If you do not agree, do not use the service.
        </div>

        <div className="space-y-10">
          <Section title="1. Nature of Service">
            <p>
              Astra is an AI-assisted accounting <strong>software tool</strong>, not an accounting firm, registered tax agent, licensed financial advisor, legal practice, or financial institution. Astra does not provide professional accounting advice, tax advice, legal advice, employment advice, or financial advice. No output from Astra — whether generated by AI, deterministic algorithms, or any combination — should be treated as professional advice.
            </p>
          </Section>

          <Section title="2. AI-Generated Output Disclaimer">
            <h3 className="font-semibold text-gray-900 mt-4 mb-2">2.1 Human Review Required</h3>
            <p>
              All AI-generated outputs — including but not limited to transaction categorisations, financial narratives, tax calculations, payroll figures, forensic analysis findings, financial health scores, spend monitoring alerts, due diligence reports, and incorporation guidance — are <strong>drafts requiring human review and approval</strong> before any reliance or action.
            </p>
            <h3 className="font-semibold text-gray-900 mt-4 mb-2">2.2 No Guarantee of Accuracy</h3>
            <p>
              While Astra's tax and payroll engines use deterministic logic derived from published legislation, tax and employment law is complex and subject to interpretation, amendment, and jurisdiction-specific exceptions. AI-generated categorisations and narratives are probabilistic and may contain errors, omissions, or hallucinations. <strong>You are solely responsible for verifying all outputs before use.</strong>
            </p>
            <h3 className="font-semibold text-gray-900 mt-4 mb-2">2.3 Not a Substitute for Professional Advice</h3>
            <p>
              Astra does not replace the need for a qualified accountant, registered tax agent, CPA, payroll specialist, solicitor, or auditor. For material financial decisions, tax filings, payroll processing, regulatory compliance, corporate formation, or legal matters, you must consult with appropriately licensed professionals in your jurisdiction.
            </p>
          </Section>

          <Section title="3. Limitation of Liability">
            <div className="bg-gray-50 rounded-xl p-4 text-xs text-gray-600 uppercase tracking-wide leading-relaxed mb-4">
              TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, ASTRA AND ITS OPERATORS, DIRECTORS, EMPLOYEES, AND AFFILIATES SHALL NOT BE LIABLE FOR ANY LOSSES, DAMAGES, PENALTIES, FINES, INTEREST, BACK-PAY OBLIGATIONS, OR COSTS ARISING FROM:
            </div>
            <ul className="space-y-2 text-sm">
              {[
                'Reliance on AI-generated categorisations, calculations, or recommendations',
                'Tax filing errors, omissions, late lodgements, or rejection by a tax authority',
                'Incorrect treaty application or withholding tax calculations',
                'Payroll miscalculations including incorrect withholdings, superannuation, pension, 401(k), or leave entitlements',
                'Forensic analysis findings (false positives or missed red flags)',
                'Spend monitoring alerts (false positives or missed fraud indicators)',
                'Financial health score inaccuracies or omissions',
                'Company incorporation guidance that is incomplete, incorrect, or inapplicable',
                'Any AI hallucination, misclassification, or erroneous output',
                'Bank feed data that is incomplete, delayed, or incorrect',
                'Receipt scanning, OCR, or expense categorisation errors',
                'Regulatory or legislative changes not yet reflected in the system',
                'System downtime, data loss, or service interruptions',
                'Actions taken by third-party integrations connected through Astra',
              ].map((item, i) => (
                <li key={i} className="flex items-start gap-2 text-gray-600">
                  <span className="text-red-400 mt-0.5">&#8226;</span> {item}
                </li>
              ))}
            </ul>
            <p className="mt-4 font-semibold text-sm">
              Liability is capped at the fees paid by you in the twelve (12) months preceding the claim. No indirect, incidental, special, consequential, exemplary, or punitive damages.
            </p>
          </Section>

          <Section title="4. Your Responsibilities">
            <ul className="space-y-2">
              {[
                'Review all AI-drafted transactions before approving them',
                'Verify tax calculations against current legislation or with a tax professional',
                'Verify payroll calculations, withholdings, and entitlements before processing pay runs',
                'Not auto-approve AI outputs without human review',
                'Maintain your own records independent of Astra',
                'Reconcile bank feed data against official bank statements',
                'Ensure your use complies with all applicable laws and regulations',
                'Maintain engagement with qualified professionals for material matters',
              ].map((item, i) => (
                <li key={i} className="flex items-start gap-2 text-gray-600">
                  <span className="text-indigo-500">&#8226;</span> {item}
                </li>
              ))}
            </ul>
          </Section>

          <Section title="5. Feature-Specific Terms">
            <div className="space-y-4">
              <FeatureTerms title="5.1 Forensic Module" items={[
                'Outputs are investigative aids, not legal evidence.',
                'Findings must be independently verified before use in any legal, regulatory, or employment context.',
                'The absence of flags does not guarantee the absence of fraud.',
              ]} />
              <FeatureTerms title="5.2 Payroll Module" items={[
                'You are solely responsible for verifying all pay calculations before processing.',
                'Incorrect payroll may result in penalties, back-pay, or legal action. Astra accepts no liability.',
                'Astra does not lodge payroll tax returns or super payments on your behalf unless you explicitly initiate lodgement.',
              ]} />
              <FeatureTerms title="5.3 Tax Filing Module" items={[
                'Tax returns are drafts for professional review.',
                'You must have a registered tax agent or CPA review before lodgement.',
                'Astra does not guarantee acceptance by any tax authority.',
              ]} />
              <FeatureTerms title="5.4 Spend Monitoring" items={[
                'Alerts do not confirm misconduct. Always investigate and follow employment law.',
                'You must not take disciplinary or legal action based solely on automated alerts.',
                'Astra accepts no liability for wrongful termination or defamation claims.',
              ]} />
              <FeatureTerms title="5.5 Financial Health Score" items={[
                'Not a credit score, credit rating, or business valuation.',
                'Do not provide to lenders or investors without independent verification.',
                'May not reflect all material risks or off-balance-sheet items.',
              ]} />
              <FeatureTerms title="5.6 Company Incorporation" items={[
                'General guidance and templates only — not legal advice.',
                'Astra does not register companies with any government authority.',
                'Engage a qualified solicitor before forming any legal entity.',
              ]} />
              <FeatureTerms title="5.7 Expense Management & Live Receipt" items={[
                'AI-based receipt scanning and categorisation may contain errors.',
                'You are responsible for reviewing all captured data before approving.',
                'Astra does not validate the legitimacy of expense claims.',
              ]} />
            </div>
          </Section>

          <Section title="6. Data Ownership & Privacy">
            <p>
              <strong>You own your data.</strong> All financial data, documents, and records remain your property. Data may be processed by third-party providers (Anthropic, Plaid, Basiq, TrueLayer, Stripe) under their respective terms. Data is not used for AI model training.
            </p>
          </Section>

          <Section title="7. Disclaimer of Warranties">
            <div className="bg-gray-50 rounded-xl p-4 text-xs text-gray-600 uppercase tracking-wide leading-relaxed">
              THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, ACCURACY, COMPLETENESS, AND NON-INFRINGEMENT.
            </div>
          </Section>

          <Section title="8. Indemnification">
            <p>
              You agree to indemnify, defend, and hold harmless Astra, its operators, directors, employees, and affiliates from any claims, damages, losses, penalties, and expenses arising from your use of the service, including claims from your employees, contractors, clients, or counterparties.
            </p>
          </Section>

          <Section title="9. Dispute Resolution">
            <p>
              These Terms are governed by the laws of New South Wales, Australia. Disputes shall be resolved through binding arbitration. Class action waiver applies to the maximum extent permitted by law.
            </p>
          </Section>

          <Section title="10. Changes & Severability">
            <p>
              Astra may modify these Terms with 30 days notice. Continued use constitutes acceptance. If any provision is found unenforceable, the remaining provisions continue in full force.
            </p>
          </Section>

          <Section title="11. Contact">
            <p>
              Legal: <span className="text-indigo-600 font-medium">legal@astra.ai</span> &middot;
              Privacy: <span className="text-indigo-600 font-medium">privacy@astra.ai</span> &middot;
              Security: <span className="text-indigo-600 font-medium">security@astra.ai</span>
            </p>
          </Section>
        </div>
      </div>
    </div>
  );
}

function Section({ title, children }) {
  return (
    <div>
      <h2 className="text-xl font-bold text-gray-900 mb-4">{title}</h2>
      <div className="text-gray-600 leading-relaxed">
        {children}
      </div>
    </div>
  );
}

function FeatureTerms({ title, items }) {
  return (
    <div className="bg-gray-50 rounded-lg p-3">
      <h4 className="font-semibold text-sm text-gray-800 mb-2">{title}</h4>
      <ul className="space-y-1">
        {items.map((item, i) => (
          <li key={i} className="text-xs text-gray-600 flex items-start gap-1.5">
            <span className="text-gray-400 mt-0.5">&#8226;</span> {item}
          </li>
        ))}
      </ul>
    </div>
  );
}
