"""Legal disclaimers attached to every AI and tax output.

Every response that contains AI-generated content or tax calculations
carries a machine-readable disclaimer. This is our legal shield.
"""

# Appended to all AI-generated outputs
AI_OUTPUT_DISCLAIMER = (
    "This output was generated by an AI system and is provided as a draft "
    "for human review only. It does not constitute professional accounting, "
    "tax, legal, or financial advice. You must verify all information with "
    "a qualified professional before reliance or action. AlecRae and its "
    "operators accept no liability for decisions made based on AI outputs."
)

# Appended to tax calculations
TAX_CALCULATION_DISCLAIMER = (
    "Tax calculations are based on published legislation as of the effective "
    "date shown. Tax law is complex and subject to interpretation, amendment, "
    "and judicial decisions. These calculations are for informational purposes "
    "only and do not constitute tax advice. Consult a qualified tax professional "
    "before filing or making decisions based on these figures."
)

# Appended to forensic analysis
FORENSIC_DISCLAIMER = (
    "Forensic analysis findings are investigative aids produced by statistical "
    "methods and AI analysis. They indicate but do not prove fraud, irregularities, "
    "or misconduct. Findings must be independently verified by qualified forensic "
    "accountants before use in any legal, regulatory, or transactional context. "
    "The absence of flags does not guarantee the absence of issues."
)

# Appended to due diligence reports
DUE_DILIGENCE_DISCLAIMER = (
    "This due diligence report is a preliminary screening tool and does not "
    "replace comprehensive due diligence by qualified professionals. Acquisition "
    "decisions, valuations, and contractual terms should never be based solely on "
    "this report. AlecRae accepts no liability for investment or acquisition losses."
)

# For bank feed data
BANK_FEED_DISCLAIMER = (
    "Bank feed data is provided by third-party aggregation services and may be "
    "incomplete, delayed, or contain errors. AlecRae does not guarantee the accuracy "
    "or completeness of bank feed data. Always reconcile against official bank statements."
)

# Payroll calculations
PAYROLL_DISCLAIMER = (
    "Payroll calculations are based on published tax tables, award rates, and "
    "superannuation/pension/retirement contribution rules as of the date shown. "
    "Legislation changes frequently and obligations vary by jurisdiction, employee "
    "classification, and individual circumstances. This tool does not constitute "
    "employment or tax advice. You are responsible for verifying all pay calculations, "
    "withholdings, superannuation contributions, and lodgements with the relevant "
    "authorities. Incorrect payroll processing may result in penalties, back-pay "
    "obligations, or legal action. Consult a qualified payroll professional."
)

# Company incorporation / formation
INCORPORATION_DISCLAIMER = (
    "Company formation tools provide general guidance and document templates only. "
    "They do not constitute legal advice. Corporate structures, director duties, "
    "compliance obligations, and registration requirements vary significantly by "
    "jurisdiction and individual circumstances. AlecRae does not register companies "
    "with any government authority on your behalf. You must engage a qualified "
    "solicitor, corporate advisor, or registered agent before forming any legal entity. "
    "AlecRae accepts no liability for entity structure decisions or regulatory non-compliance."
)

# Financial Health Score
FINANCIAL_HEALTH_DISCLAIMER = (
    "The Financial Health Score is an indicative assessment calculated from your "
    "accounting data. It is not a credit score, credit rating, business valuation, "
    "or guarantee of financial performance. Do not rely on this score for loan "
    "applications, investment decisions, business acquisitions, or any financial "
    "commitment without independent professional verification. The score may not "
    "reflect all material risks, off-balance-sheet items, or contingent liabilities."
)

# Spend monitoring / fraud alerts
SPEND_MONITOR_DISCLAIMER = (
    "Fraud alerts are generated by automated rules and statistical pattern analysis. "
    "An alert does not confirm misconduct, theft, or policy violation — it flags "
    "transactions for human review. Do not take disciplinary, termination, or legal "
    "action based solely on automated alerts. Always investigate thoroughly, provide "
    "the employee an opportunity to explain, and follow your jurisdiction's employment "
    "and privacy laws before acting. False positives can and will occur."
)

# Tax filing / lodgement
TAX_FILING_DISCLAIMER = (
    "Tax returns generated by this system are drafts for professional review. You are "
    "solely responsible for the accuracy and completeness of any return lodged with a "
    "tax authority. AlecRae does not guarantee acceptance by any tax authority. Incorrect "
    "filings may result in penalties, interest charges, or audit. Have a registered tax "
    "agent, CPA, or qualified tax professional review all returns before lodgement."
)


def get_disclaimer(output_type: str) -> str:
    """Get the appropriate disclaimer for an output type."""
    disclaimers = {
        "ai": AI_OUTPUT_DISCLAIMER,
        "tax": TAX_CALCULATION_DISCLAIMER,
        "tax_filing": TAX_FILING_DISCLAIMER,
        "forensic": FORENSIC_DISCLAIMER,
        "due_diligence": DUE_DILIGENCE_DISCLAIMER,
        "bank_feed": BANK_FEED_DISCLAIMER,
        "payroll": PAYROLL_DISCLAIMER,
        "incorporation": INCORPORATION_DISCLAIMER,
        "financial_health": FINANCIAL_HEALTH_DISCLAIMER,
        "spend_monitor": SPEND_MONITOR_DISCLAIMER,
    }
    return disclaimers.get(output_type, AI_OUTPUT_DISCLAIMER)


def wrap_response(data: dict, output_type: str, ai_generated: bool = False) -> dict:
    """Wrap any API response with legal metadata.

    Every response includes:
    - disclaimer: human-readable legal disclaimer
    - ai_generated: whether AI was involved
    - requires_review: whether human review is required before action
    - liability_accepted: always False (user must explicitly accept)
    """
    return {
        **data,
        "_legal": {
            "disclaimer": get_disclaimer(output_type),
            "ai_generated": ai_generated,
            "requires_human_review": ai_generated or output_type in ("forensic", "due_diligence"),
            "liability_accepted": False,
            "output_type": output_type,
        },
    }
