"""Legal disclaimers attached to every AI and tax output.

Every response that contains AI-generated content or tax calculations
carries a machine-readable disclaimer. This is our legal shield.
"""

# Appended to all AI-generated outputs
AI_OUTPUT_DISCLAIMER = (
    "This output was generated by an AI system and is provided as a draft "
    "for human review only. It does not constitute professional accounting, "
    "tax, legal, or financial advice. You must verify all information with "
    "a qualified professional before reliance or action. Astra and its "
    "operators accept no liability for decisions made based on AI outputs."
)

# Appended to tax calculations
TAX_CALCULATION_DISCLAIMER = (
    "Tax calculations are based on published legislation as of the effective "
    "date shown. Tax law is complex and subject to interpretation, amendment, "
    "and judicial decisions. These calculations are for informational purposes "
    "only and do not constitute tax advice. Consult a qualified tax professional "
    "before filing or making decisions based on these figures."
)

# Appended to forensic analysis
FORENSIC_DISCLAIMER = (
    "Forensic analysis findings are investigative aids produced by statistical "
    "methods and AI analysis. They indicate but do not prove fraud, irregularities, "
    "or misconduct. Findings must be independently verified by qualified forensic "
    "accountants before use in any legal, regulatory, or transactional context. "
    "The absence of flags does not guarantee the absence of issues."
)

# Appended to due diligence reports
DUE_DILIGENCE_DISCLAIMER = (
    "This due diligence report is a preliminary screening tool and does not "
    "replace comprehensive due diligence by qualified professionals. Acquisition "
    "decisions, valuations, and contractual terms should never be based solely on "
    "this report. Astra accepts no liability for investment or acquisition losses."
)

# For bank feed data
BANK_FEED_DISCLAIMER = (
    "Bank feed data is provided by third-party aggregation services and may be "
    "incomplete, delayed, or contain errors. Astra does not guarantee the accuracy "
    "or completeness of bank feed data. Always reconcile against official bank statements."
)


def get_disclaimer(output_type: str) -> str:
    """Get the appropriate disclaimer for an output type."""
    disclaimers = {
        "ai": AI_OUTPUT_DISCLAIMER,
        "tax": TAX_CALCULATION_DISCLAIMER,
        "forensic": FORENSIC_DISCLAIMER,
        "due_diligence": DUE_DILIGENCE_DISCLAIMER,
        "bank_feed": BANK_FEED_DISCLAIMER,
    }
    return disclaimers.get(output_type, AI_OUTPUT_DISCLAIMER)


def wrap_response(data: dict, output_type: str, ai_generated: bool = False) -> dict:
    """Wrap any API response with legal metadata.

    Every response includes:
    - disclaimer: human-readable legal disclaimer
    - ai_generated: whether AI was involved
    - requires_review: whether human review is required before action
    - liability_accepted: always False (user must explicitly accept)
    """
    return {
        **data,
        "_legal": {
            "disclaimer": get_disclaimer(output_type),
            "ai_generated": ai_generated,
            "requires_human_review": ai_generated or output_type in ("forensic", "due_diligence"),
            "liability_accepted": False,
            "output_type": output_type,
        },
    }
